//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzyLiveWebsiteMain.Models.owner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Web;

    public partial class Owner
    {
        public int Id { get; set; }
        [DisplayName("Name")]
        public string name { get; set; }
        [DisplayName("Email")]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Invalid Email")]

        public string email { get; set; }
        [DisplayName("Contact Number")]
        public string contact { get; set; }
        [DisplayName("Address")]
        public string address { get; set; }
        [DisplayName("Select Image")]
        public string image { get; set; }
      
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
