//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzyLiveWebsiteMain.Models.Contact
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
       
        public int Id { get; set; }
        [Required(ErrorMessage = ("Name is Required"))]
        public string name { get; set; }

        [Required(ErrorMessage = ("Email is Required"))]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Invalid Email")]

        public string email { get; set; }
        [Required(ErrorMessage = ("Phone No. is Required"))]
        public string phone { get; set; }
        [Required(ErrorMessage = ("Message is Required"))]
        public string message { get; set; }
    }
}
